spring.application.name=FamilySpin
server.port=8081
family.spin.members=Mere Regine, Daddy Chriss, Arsene, Festus, Paccy, kevine, Kevin, Daniel, ange, Divine Muto, Divine Mukuru, Egide, Penuelle, Caline, Ebenezel, Theophilus, Emelyne, Coco, Vava, Raymond, Yva, Yves, Caleddy, Moise, Simba, Yannick, Irene, Esther, Lenatha, Janvier,J Aime, Christian, Elysee, Florence, Eric, Gihozo, Honore
family.spin.weekly-cron=0 0 0 * * MON
# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true